language: go

go:
  - 1.2.2
  - 1.3.3
  - 1.4.2
  - 1.5.1
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/tools/godep
script:
    - make bench
    - make test
    - make detail
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
